import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import { useAutoLogout } from "./hook/UseAutoLogout";
import AutoLogoutProvider from "@/components/AutoLogoutProvider";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Sistem Work Permit - PT. Eksavindo Mitra Mandiri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <AutoLogoutProvider />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
